// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stress.proto

package com.example.agentgrpc.protocol.stress;

/**
 * Protobuf type {@code agent.JsonResultReq}
 */
public final class JsonResultReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:agent.JsonResultReq)
    JsonResultReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JsonResultReq.newBuilder() to construct.
  private JsonResultReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JsonResultReq() {
    execId_ = "";
    filterName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JsonResultReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JsonResultReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            execId_ = s;
            break;
          }
          case 16: {

            index_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            filterName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.agentgrpc.protocol.stress.StressOuterClass.internal_static_agent_JsonResultReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.agentgrpc.protocol.stress.StressOuterClass.internal_static_agent_JsonResultReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.agentgrpc.protocol.stress.JsonResultReq.class, com.example.agentgrpc.protocol.stress.JsonResultReq.Builder.class);
  }

  public static final int EXEC_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object execId_;
  /**
   * <code>string exec_id = 1;</code>
   * @return The execId.
   */
  @java.lang.Override
  public java.lang.String getExecId() {
    java.lang.Object ref = execId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      execId_ = s;
      return s;
    }
  }
  /**
   * <code>string exec_id = 1;</code>
   * @return The bytes for execId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExecIdBytes() {
    java.lang.Object ref = execId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      execId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INDEX_FIELD_NUMBER = 2;
  private int index_;
  /**
   * <pre>
   *当前任务在任务队列中的索引
   * </pre>
   *
   * <code>int32 index = 2;</code>
   * @return The index.
   */
  @java.lang.Override
  public int getIndex() {
    return index_;
  }

  public static final int FILTER_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object filterName_;
  /**
   * <pre>
   *处理的filter
   * </pre>
   *
   * <code>string filter_name = 3;</code>
   * @return The filterName.
   */
  @java.lang.Override
  public java.lang.String getFilterName() {
    java.lang.Object ref = filterName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filterName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *处理的filter
   * </pre>
   *
   * <code>string filter_name = 3;</code>
   * @return The bytes for filterName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilterNameBytes() {
    java.lang.Object ref = filterName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filterName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(execId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, execId_);
    }
    if (index_ != 0) {
      output.writeInt32(2, index_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filterName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, filterName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(execId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, execId_);
    }
    if (index_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, index_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filterName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, filterName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.agentgrpc.protocol.stress.JsonResultReq)) {
      return super.equals(obj);
    }
    com.example.agentgrpc.protocol.stress.JsonResultReq other = (com.example.agentgrpc.protocol.stress.JsonResultReq) obj;

    if (!getExecId()
        .equals(other.getExecId())) return false;
    if (getIndex()
        != other.getIndex()) return false;
    if (!getFilterName()
        .equals(other.getFilterName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXEC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getExecId().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex();
    hash = (37 * hash) + FILTER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFilterName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.agentgrpc.protocol.stress.JsonResultReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.agentgrpc.protocol.stress.JsonResultReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.agentgrpc.protocol.stress.JsonResultReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.agentgrpc.protocol.stress.JsonResultReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.agentgrpc.protocol.stress.JsonResultReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.agentgrpc.protocol.stress.JsonResultReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.agentgrpc.protocol.stress.JsonResultReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.agentgrpc.protocol.stress.JsonResultReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.agentgrpc.protocol.stress.JsonResultReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.agentgrpc.protocol.stress.JsonResultReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.agentgrpc.protocol.stress.JsonResultReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.agentgrpc.protocol.stress.JsonResultReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.agentgrpc.protocol.stress.JsonResultReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code agent.JsonResultReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.JsonResultReq)
      com.example.agentgrpc.protocol.stress.JsonResultReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.agentgrpc.protocol.stress.StressOuterClass.internal_static_agent_JsonResultReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.agentgrpc.protocol.stress.StressOuterClass.internal_static_agent_JsonResultReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.agentgrpc.protocol.stress.JsonResultReq.class, com.example.agentgrpc.protocol.stress.JsonResultReq.Builder.class);
    }

    // Construct using com.example.agentgrpc.protocol.stress.JsonResultReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      execId_ = "";

      index_ = 0;

      filterName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.agentgrpc.protocol.stress.StressOuterClass.internal_static_agent_JsonResultReq_descriptor;
    }

    @java.lang.Override
    public com.example.agentgrpc.protocol.stress.JsonResultReq getDefaultInstanceForType() {
      return com.example.agentgrpc.protocol.stress.JsonResultReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.agentgrpc.protocol.stress.JsonResultReq build() {
      com.example.agentgrpc.protocol.stress.JsonResultReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.agentgrpc.protocol.stress.JsonResultReq buildPartial() {
      com.example.agentgrpc.protocol.stress.JsonResultReq result = new com.example.agentgrpc.protocol.stress.JsonResultReq(this);
      result.execId_ = execId_;
      result.index_ = index_;
      result.filterName_ = filterName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.agentgrpc.protocol.stress.JsonResultReq) {
        return mergeFrom((com.example.agentgrpc.protocol.stress.JsonResultReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.agentgrpc.protocol.stress.JsonResultReq other) {
      if (other == com.example.agentgrpc.protocol.stress.JsonResultReq.getDefaultInstance()) return this;
      if (!other.getExecId().isEmpty()) {
        execId_ = other.execId_;
        onChanged();
      }
      if (other.getIndex() != 0) {
        setIndex(other.getIndex());
      }
      if (!other.getFilterName().isEmpty()) {
        filterName_ = other.filterName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.agentgrpc.protocol.stress.JsonResultReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.agentgrpc.protocol.stress.JsonResultReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object execId_ = "";
    /**
     * <code>string exec_id = 1;</code>
     * @return The execId.
     */
    public java.lang.String getExecId() {
      java.lang.Object ref = execId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        execId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string exec_id = 1;</code>
     * @return The bytes for execId.
     */
    public com.google.protobuf.ByteString
        getExecIdBytes() {
      java.lang.Object ref = execId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        execId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string exec_id = 1;</code>
     * @param value The execId to set.
     * @return This builder for chaining.
     */
    public Builder setExecId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      execId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string exec_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecId() {
      
      execId_ = getDefaultInstance().getExecId();
      onChanged();
      return this;
    }
    /**
     * <code>string exec_id = 1;</code>
     * @param value The bytes for execId to set.
     * @return This builder for chaining.
     */
    public Builder setExecIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      execId_ = value;
      onChanged();
      return this;
    }

    private int index_ ;
    /**
     * <pre>
     *当前任务在任务队列中的索引
     * </pre>
     *
     * <code>int32 index = 2;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }
    /**
     * <pre>
     *当前任务在任务队列中的索引
     * </pre>
     *
     * <code>int32 index = 2;</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(int value) {
      
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *当前任务在任务队列中的索引
     * </pre>
     *
     * <code>int32 index = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      
      index_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object filterName_ = "";
    /**
     * <pre>
     *处理的filter
     * </pre>
     *
     * <code>string filter_name = 3;</code>
     * @return The filterName.
     */
    public java.lang.String getFilterName() {
      java.lang.Object ref = filterName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filterName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *处理的filter
     * </pre>
     *
     * <code>string filter_name = 3;</code>
     * @return The bytes for filterName.
     */
    public com.google.protobuf.ByteString
        getFilterNameBytes() {
      java.lang.Object ref = filterName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filterName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *处理的filter
     * </pre>
     *
     * <code>string filter_name = 3;</code>
     * @param value The filterName to set.
     * @return This builder for chaining.
     */
    public Builder setFilterName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filterName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *处理的filter
     * </pre>
     *
     * <code>string filter_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilterName() {
      
      filterName_ = getDefaultInstance().getFilterName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *处理的filter
     * </pre>
     *
     * <code>string filter_name = 3;</code>
     * @param value The bytes for filterName to set.
     * @return This builder for chaining.
     */
    public Builder setFilterNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filterName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:agent.JsonResultReq)
  }

  // @@protoc_insertion_point(class_scope:agent.JsonResultReq)
  private static final com.example.agentgrpc.protocol.stress.JsonResultReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.agentgrpc.protocol.stress.JsonResultReq();
  }

  public static com.example.agentgrpc.protocol.stress.JsonResultReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JsonResultReq>
      PARSER = new com.google.protobuf.AbstractParser<JsonResultReq>() {
    @java.lang.Override
    public JsonResultReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JsonResultReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JsonResultReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JsonResultReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.agentgrpc.protocol.stress.JsonResultReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

