// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stress.proto

package com.example.agentgrpc.protocol.stress;

public interface StopStressReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.StopStressReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string exec_id = 1;</code>
   * @return The execId.
   */
  java.lang.String getExecId();
  /**
   * <code>string exec_id = 1;</code>
   * @return The bytes for execId.
   */
  com.google.protobuf.ByteString
      getExecIdBytes();

  /**
   * <pre>
   *当前任务在任务队列中的索引
   * </pre>
   *
   * <code>int32 index = 2;</code>
   * @return The index.
   */
  int getIndex();
}
