// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stress.proto

package com.example.agentgrpc.protocol.stress;

public final class StressOuterClass {
  private StressOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_StartStressReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_StartStressReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_StartStressRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_StartStressRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_StopStressReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_StopStressReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_StopStressRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_StopStressRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_JsonResultReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_JsonResultReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_JsonResultRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_JsonResultRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014stress.proto\022\005agent\"Y\n\016StartStressReq\022" +
      "\017\n\007exec_id\030\001 \001(\t\022\r\n\005index\030\002 \001(\005\022\024\n\014downl" +
      "oad_url\030\003 \001(\t\022\021\n\tfile_list\030\004 \003(\t\"/\n\016Star" +
      "tStressRes\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(" +
      "\t\"/\n\rStopStressReq\022\017\n\007exec_id\030\001 \001(\t\022\r\n\005i" +
      "ndex\030\002 \001(\005\".\n\rStopStressRes\022\014\n\004code\030\001 \001(" +
      "\005\022\017\n\007message\030\002 \001(\t\"D\n\rJsonResultReq\022\017\n\007e" +
      "xec_id\030\001 \001(\t\022\r\n\005index\030\002 \001(\005\022\023\n\013filter_na" +
      "me\030\003 \001(\t\"P\n\rJsonResultRes\022\014\n\004code\030\001 \001(\005\022" +
      "\017\n\007message\030\002 \001(\t\022\021\n\tfile_name\030\003 \001(\t\022\r\n\005c" +
      "hunk\030\004 \001(\t2\301\001\n\006Stress\022=\n\013StartStress\022\025.a" +
      "gent.StartStressReq\032\025.agent.StartStressR" +
      "es\"\000\022:\n\nStopStress\022\024.agent.StopStressReq" +
      "\032\024.agent.StopStressRes\"\000\022<\n\nJsonResult\022\024" +
      ".agent.JsonResultReq\032\024.agent.JsonResultR" +
      "es\"\0000\001B<\n%com.example.agentgrpc.protocol" +
      ".stressP\001Z\021protocol/v1/agentb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_agent_StartStressReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_agent_StartStressReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_StartStressReq_descriptor,
        new java.lang.String[] { "ExecId", "Index", "DownloadUrl", "FileList", });
    internal_static_agent_StartStressRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_agent_StartStressRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_StartStressRes_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_agent_StopStressReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_agent_StopStressReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_StopStressReq_descriptor,
        new java.lang.String[] { "ExecId", "Index", });
    internal_static_agent_StopStressRes_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_agent_StopStressRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_StopStressRes_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_agent_JsonResultReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_agent_JsonResultReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_JsonResultReq_descriptor,
        new java.lang.String[] { "ExecId", "Index", "FilterName", });
    internal_static_agent_JsonResultRes_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_agent_JsonResultRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_JsonResultRes_descriptor,
        new java.lang.String[] { "Code", "Message", "FileName", "Chunk", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
