// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent.proto

package com.example.agentgrpc.protocol.agent;

public interface UpdateAgentReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.UpdateAgentReq)
    com.google.protobuf.MessageOrBuilder {
}
