// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent.proto

package com.example.agentgrpc.protocol.agent;

public interface UpdateAgentReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.UpdateAgentReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string exec_id = 1;</code>
   * @return The execId.
   */
  java.lang.String getExecId();
  /**
   * <code>string exec_id = 1;</code>
   * @return The bytes for execId.
   */
  com.google.protobuf.ByteString
      getExecIdBytes();

  /**
   * <code>int32 index = 2;</code>
   * @return The index.
   */
  int getIndex();
}
