// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: debug.proto

package com.example.agentgrpc.protocol.debug;

public interface ContextReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.ContextReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string req = 1;</code>
   * @return The req.
   */
  java.lang.String getReq();
  /**
   * <code>string req = 1;</code>
   * @return The bytes for req.
   */
  com.google.protobuf.ByteString
      getReqBytes();
}
