// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: debug.proto

package com.example.agentgrpc.protocol.debug;

public interface ContextResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.ContextRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string res = 1;</code>
   * @return The res.
   */
  java.lang.String getRes();
  /**
   * <code>string res = 1;</code>
   * @return The bytes for res.
   */
  com.google.protobuf.ByteString
      getResBytes();
}
