// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: debug.proto

package com.example.agentgrpc.protocol.debug;

public final class DebugOuterClass {
  private DebugOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_ContextReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_ContextReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_ContextRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_ContextRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013debug.proto\022\005agent\"\031\n\nContextReq\022\013\n\003re" +
      "q\030\001 \001(\t\"\031\n\nContextRes\022\013\n\003res\030\001 \001(\t2D\n\005De" +
      "bug\022;\n\021GetServletContext\022\021.agent.Context" +
      "Req\032\021.agent.ContextRes\"\000B;\n$com.example." +
      "agentgrpc.protocol.debugP\001Z\021protocol/v1/" +
      "agentb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_agent_ContextReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_agent_ContextReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_ContextReq_descriptor,
        new java.lang.String[] { "Req", });
    internal_static_agent_ContextRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_agent_ContextRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_ContextRes_descriptor,
        new java.lang.String[] { "Res", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
