// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Collector.proto

package com.example.agentgrpc.protocol.collector;

public interface AgentStatusResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:platform.AgentStatusRes)
    com.google.protobuf.MessageOrBuilder {
}
