// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Collector.proto

package com.example.agentgrpc.protocol.collector;

public interface AgentStatusReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:platform.AgentStatusReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *暂定，id/name/ip等
   * </pre>
   *
   * <code>string agent_Id = 1;</code>
   * @return The agentId.
   */
  java.lang.String getAgentId();
  /**
   * <pre>
   *暂定，id/name/ip等
   * </pre>
   *
   * <code>string agent_Id = 1;</code>
   * @return The bytes for agentId.
   */
  com.google.protobuf.ByteString
      getAgentIdBytes();

  /**
   * <pre>
   *状态，空闲/正在执行任务
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   *状态，空闲/正在执行任务
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <pre>
   *正在执行的任务列表
   * </pre>
   *
   * <code>repeated .platform.TaskList exec_list = 3;</code>
   */
  java.util.List<com.example.agentgrpc.protocol.collector.TaskList> 
      getExecListList();
  /**
   * <pre>
   *正在执行的任务列表
   * </pre>
   *
   * <code>repeated .platform.TaskList exec_list = 3;</code>
   */
  com.example.agentgrpc.protocol.collector.TaskList getExecList(int index);
  /**
   * <pre>
   *正在执行的任务列表
   * </pre>
   *
   * <code>repeated .platform.TaskList exec_list = 3;</code>
   */
  int getExecListCount();
  /**
   * <pre>
   *正在执行的任务列表
   * </pre>
   *
   * <code>repeated .platform.TaskList exec_list = 3;</code>
   */
  java.util.List<? extends com.example.agentgrpc.protocol.collector.TaskListOrBuilder> 
      getExecListOrBuilderList();
  /**
   * <pre>
   *正在执行的任务列表
   * </pre>
   *
   * <code>repeated .platform.TaskList exec_list = 3;</code>
   */
  com.example.agentgrpc.protocol.collector.TaskListOrBuilder getExecListOrBuilder(
      int index);
}
