// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Collector.proto

package com.example.agentgrpc.protocol.collector;

public final class CollectorOuterClass {
  private CollectorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_AgentStatusReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_AgentStatusReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_TaskList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_TaskList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_AgentStatusRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_AgentStatusRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_TaskStatusReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_TaskStatusReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_TaskStatusRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_TaskStatusRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Collector.proto\022\010platform\"Y\n\016AgentStat" +
      "usReq\022\020\n\010agent_Id\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\022" +
      "%\n\texec_list\030\003 \003(\0132\022.platform.TaskList\"\033" +
      "\n\010TaskList\022\017\n\007exec_id\030\001 \001(\t\"\020\n\016AgentStat" +
      "usRes\"`\n\rTaskStatusReq\022\017\n\007exec_id\030\001 \001(\t\022" +
      "\r\n\005index\030\002 \001(\005\022\020\n\010job_type\030\003 \001(\005\022\014\n\004code" +
      "\030\004 \001(\005\022\017\n\007message\030\005 \001(\t\"\017\n\rTaskStatusRes" +
      "2\222\001\n\tCollector\022C\n\013AgentStatus\022\030.platform" +
      ".AgentStatusReq\032\030.platform.AgentStatusRe" +
      "s\"\000\022@\n\nTaskStatus\022\027.platform.TaskStatusR" +
      "eq\032\027.platform.TaskStatusRes\"\000B,\n(com.exa" +
      "mple.agentgrpc.protocol.collectorP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_platform_AgentStatusReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_platform_AgentStatusReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_AgentStatusReq_descriptor,
        new java.lang.String[] { "AgentId", "Status", "ExecList", });
    internal_static_platform_TaskList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_platform_TaskList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_TaskList_descriptor,
        new java.lang.String[] { "ExecId", });
    internal_static_platform_AgentStatusRes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_platform_AgentStatusRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_AgentStatusRes_descriptor,
        new java.lang.String[] { });
    internal_static_platform_TaskStatusReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_platform_TaskStatusReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_TaskStatusReq_descriptor,
        new java.lang.String[] { "ExecId", "Index", "JobType", "Code", "Message", });
    internal_static_platform_TaskStatusRes_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_platform_TaskStatusRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_TaskStatusRes_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
