// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Collector.proto

package com.example.agentgrpc.protocol.collector;

public interface TaskStatusReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:platform.TaskStatusReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *任务id
   * </pre>
   *
   * <code>string exec_id = 1;</code>
   * @return The execId.
   */
  java.lang.String getExecId();
  /**
   * <pre>
   *任务id
   * </pre>
   *
   * <code>string exec_id = 1;</code>
   * @return The bytes for execId.
   */
  com.google.protobuf.ByteString
      getExecIdBytes();

  /**
   * <pre>
   *当前任务在任务队列中的索引
   * </pre>
   *
   * <code>int32 index = 2;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <pre>
   *job_type:
   * 1开启工程
   * 2打dump
   * 3压测结束
   * </pre>
   *
   * <code>int32 job_type = 3;</code>
   * @return The jobType.
   */
  int getJobType();

  /**
   * <code>int32 code = 4;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <pre>
   *任务执行状态，对于打dump，返回dump目录
   * </pre>
   *
   * <code>string message = 5;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   *任务执行状态，对于打dump，返回dump目录
   * </pre>
   *
   * <code>string message = 5;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
