// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Collector.proto

package com.example.agentgrpc.protocol.collector;

public interface TaskListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:platform.TaskList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *任务id
   * </pre>
   *
   * <code>string exec_id = 1;</code>
   * @return The execId.
   */
  java.lang.String getExecId();
  /**
   * <pre>
   *任务id
   * </pre>
   *
   * <code>string exec_id = 1;</code>
   * @return The bytes for execId.
   */
  com.google.protobuf.ByteString
      getExecIdBytes();
}
