// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Collector.proto

package com.example.agentgrpc.protocol.collector;

public interface TaskStatusResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:platform.TaskStatusRes)
    com.google.protobuf.MessageOrBuilder {
}
