// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: project.proto

package com.example.agentgrpc.protocol.project;

/**
 * Protobuf type {@code agent.ReplaceJarReq}
 */
public final class ReplaceJarReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:agent.ReplaceJarReq)
    ReplaceJarReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReplaceJarReq.newBuilder() to construct.
  private ReplaceJarReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReplaceJarReq() {
    execId_ = "";
    downloadUrl_ = "";
    fileList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReplaceJarReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReplaceJarReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            execId_ = s;
            break;
          }
          case 16: {

            index_ = input.readInt32();
            break;
          }
          case 26: {
            com.example.agentgrpc.protocol.project.NodeInfo.Builder subBuilder = null;
            if (node_ != null) {
              subBuilder = node_.toBuilder();
            }
            node_ = input.readMessage(com.example.agentgrpc.protocol.project.NodeInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(node_);
              node_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            downloadUrl_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              fileList_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            fileList_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        fileList_ = fileList_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.agentgrpc.protocol.project.ProjectOuterClass.internal_static_agent_ReplaceJarReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.agentgrpc.protocol.project.ProjectOuterClass.internal_static_agent_ReplaceJarReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.agentgrpc.protocol.project.ReplaceJarReq.class, com.example.agentgrpc.protocol.project.ReplaceJarReq.Builder.class);
  }

  public static final int EXEC_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object execId_;
  /**
   * <code>string exec_id = 1;</code>
   * @return The execId.
   */
  @java.lang.Override
  public java.lang.String getExecId() {
    java.lang.Object ref = execId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      execId_ = s;
      return s;
    }
  }
  /**
   * <code>string exec_id = 1;</code>
   * @return The bytes for execId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExecIdBytes() {
    java.lang.Object ref = execId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      execId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INDEX_FIELD_NUMBER = 2;
  private int index_;
  /**
   * <pre>
   *当前任务在任务队列中的索引
   * </pre>
   *
   * <code>int32 index = 2;</code>
   * @return The index.
   */
  @java.lang.Override
  public int getIndex() {
    return index_;
  }

  public static final int NODE_FIELD_NUMBER = 3;
  private com.example.agentgrpc.protocol.project.NodeInfo node_;
  /**
   * <code>.agent.NodeInfo node = 3;</code>
   * @return Whether the node field is set.
   */
  @java.lang.Override
  public boolean hasNode() {
    return node_ != null;
  }
  /**
   * <code>.agent.NodeInfo node = 3;</code>
   * @return The node.
   */
  @java.lang.Override
  public com.example.agentgrpc.protocol.project.NodeInfo getNode() {
    return node_ == null ? com.example.agentgrpc.protocol.project.NodeInfo.getDefaultInstance() : node_;
  }
  /**
   * <code>.agent.NodeInfo node = 3;</code>
   */
  @java.lang.Override
  public com.example.agentgrpc.protocol.project.NodeInfoOrBuilder getNodeOrBuilder() {
    return getNode();
  }

  public static final int DOWNLOAD_URL_FIELD_NUMBER = 4;
  private volatile java.lang.Object downloadUrl_;
  /**
   * <pre>
   *下载路径
   * </pre>
   *
   * <code>string download_url = 4;</code>
   * @return The downloadUrl.
   */
  @java.lang.Override
  public java.lang.String getDownloadUrl() {
    java.lang.Object ref = downloadUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      downloadUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *下载路径
   * </pre>
   *
   * <code>string download_url = 4;</code>
   * @return The bytes for downloadUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDownloadUrlBytes() {
    java.lang.Object ref = downloadUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      downloadUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILE_LIST_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList fileList_;
  /**
   * <pre>
   *文件列表
   * </pre>
   *
   * <code>repeated string file_list = 5;</code>
   * @return A list containing the fileList.
   */
  public com.google.protobuf.ProtocolStringList
      getFileListList() {
    return fileList_;
  }
  /**
   * <pre>
   *文件列表
   * </pre>
   *
   * <code>repeated string file_list = 5;</code>
   * @return The count of fileList.
   */
  public int getFileListCount() {
    return fileList_.size();
  }
  /**
   * <pre>
   *文件列表
   * </pre>
   *
   * <code>repeated string file_list = 5;</code>
   * @param index The index of the element to return.
   * @return The fileList at the given index.
   */
  public java.lang.String getFileList(int index) {
    return fileList_.get(index);
  }
  /**
   * <pre>
   *文件列表
   * </pre>
   *
   * <code>repeated string file_list = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the fileList at the given index.
   */
  public com.google.protobuf.ByteString
      getFileListBytes(int index) {
    return fileList_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(execId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, execId_);
    }
    if (index_ != 0) {
      output.writeInt32(2, index_);
    }
    if (node_ != null) {
      output.writeMessage(3, getNode());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(downloadUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, downloadUrl_);
    }
    for (int i = 0; i < fileList_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, fileList_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(execId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, execId_);
    }
    if (index_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, index_);
    }
    if (node_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getNode());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(downloadUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, downloadUrl_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < fileList_.size(); i++) {
        dataSize += computeStringSizeNoTag(fileList_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFileListList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.agentgrpc.protocol.project.ReplaceJarReq)) {
      return super.equals(obj);
    }
    com.example.agentgrpc.protocol.project.ReplaceJarReq other = (com.example.agentgrpc.protocol.project.ReplaceJarReq) obj;

    if (!getExecId()
        .equals(other.getExecId())) return false;
    if (getIndex()
        != other.getIndex()) return false;
    if (hasNode() != other.hasNode()) return false;
    if (hasNode()) {
      if (!getNode()
          .equals(other.getNode())) return false;
    }
    if (!getDownloadUrl()
        .equals(other.getDownloadUrl())) return false;
    if (!getFileListList()
        .equals(other.getFileListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXEC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getExecId().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex();
    if (hasNode()) {
      hash = (37 * hash) + NODE_FIELD_NUMBER;
      hash = (53 * hash) + getNode().hashCode();
    }
    hash = (37 * hash) + DOWNLOAD_URL_FIELD_NUMBER;
    hash = (53 * hash) + getDownloadUrl().hashCode();
    if (getFileListCount() > 0) {
      hash = (37 * hash) + FILE_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getFileListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.agentgrpc.protocol.project.ReplaceJarReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.agentgrpc.protocol.project.ReplaceJarReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.agentgrpc.protocol.project.ReplaceJarReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.agentgrpc.protocol.project.ReplaceJarReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.agentgrpc.protocol.project.ReplaceJarReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.agentgrpc.protocol.project.ReplaceJarReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.agentgrpc.protocol.project.ReplaceJarReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.agentgrpc.protocol.project.ReplaceJarReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.agentgrpc.protocol.project.ReplaceJarReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.agentgrpc.protocol.project.ReplaceJarReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.agentgrpc.protocol.project.ReplaceJarReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.agentgrpc.protocol.project.ReplaceJarReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.agentgrpc.protocol.project.ReplaceJarReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code agent.ReplaceJarReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.ReplaceJarReq)
      com.example.agentgrpc.protocol.project.ReplaceJarReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.agentgrpc.protocol.project.ProjectOuterClass.internal_static_agent_ReplaceJarReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.agentgrpc.protocol.project.ProjectOuterClass.internal_static_agent_ReplaceJarReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.agentgrpc.protocol.project.ReplaceJarReq.class, com.example.agentgrpc.protocol.project.ReplaceJarReq.Builder.class);
    }

    // Construct using com.example.agentgrpc.protocol.project.ReplaceJarReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      execId_ = "";

      index_ = 0;

      if (nodeBuilder_ == null) {
        node_ = null;
      } else {
        node_ = null;
        nodeBuilder_ = null;
      }
      downloadUrl_ = "";

      fileList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.agentgrpc.protocol.project.ProjectOuterClass.internal_static_agent_ReplaceJarReq_descriptor;
    }

    @java.lang.Override
    public com.example.agentgrpc.protocol.project.ReplaceJarReq getDefaultInstanceForType() {
      return com.example.agentgrpc.protocol.project.ReplaceJarReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.agentgrpc.protocol.project.ReplaceJarReq build() {
      com.example.agentgrpc.protocol.project.ReplaceJarReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.agentgrpc.protocol.project.ReplaceJarReq buildPartial() {
      com.example.agentgrpc.protocol.project.ReplaceJarReq result = new com.example.agentgrpc.protocol.project.ReplaceJarReq(this);
      int from_bitField0_ = bitField0_;
      result.execId_ = execId_;
      result.index_ = index_;
      if (nodeBuilder_ == null) {
        result.node_ = node_;
      } else {
        result.node_ = nodeBuilder_.build();
      }
      result.downloadUrl_ = downloadUrl_;
      if (((bitField0_ & 0x00000001) != 0)) {
        fileList_ = fileList_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.fileList_ = fileList_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.agentgrpc.protocol.project.ReplaceJarReq) {
        return mergeFrom((com.example.agentgrpc.protocol.project.ReplaceJarReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.agentgrpc.protocol.project.ReplaceJarReq other) {
      if (other == com.example.agentgrpc.protocol.project.ReplaceJarReq.getDefaultInstance()) return this;
      if (!other.getExecId().isEmpty()) {
        execId_ = other.execId_;
        onChanged();
      }
      if (other.getIndex() != 0) {
        setIndex(other.getIndex());
      }
      if (other.hasNode()) {
        mergeNode(other.getNode());
      }
      if (!other.getDownloadUrl().isEmpty()) {
        downloadUrl_ = other.downloadUrl_;
        onChanged();
      }
      if (!other.fileList_.isEmpty()) {
        if (fileList_.isEmpty()) {
          fileList_ = other.fileList_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureFileListIsMutable();
          fileList_.addAll(other.fileList_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.agentgrpc.protocol.project.ReplaceJarReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.agentgrpc.protocol.project.ReplaceJarReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object execId_ = "";
    /**
     * <code>string exec_id = 1;</code>
     * @return The execId.
     */
    public java.lang.String getExecId() {
      java.lang.Object ref = execId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        execId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string exec_id = 1;</code>
     * @return The bytes for execId.
     */
    public com.google.protobuf.ByteString
        getExecIdBytes() {
      java.lang.Object ref = execId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        execId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string exec_id = 1;</code>
     * @param value The execId to set.
     * @return This builder for chaining.
     */
    public Builder setExecId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      execId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string exec_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecId() {
      
      execId_ = getDefaultInstance().getExecId();
      onChanged();
      return this;
    }
    /**
     * <code>string exec_id = 1;</code>
     * @param value The bytes for execId to set.
     * @return This builder for chaining.
     */
    public Builder setExecIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      execId_ = value;
      onChanged();
      return this;
    }

    private int index_ ;
    /**
     * <pre>
     *当前任务在任务队列中的索引
     * </pre>
     *
     * <code>int32 index = 2;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }
    /**
     * <pre>
     *当前任务在任务队列中的索引
     * </pre>
     *
     * <code>int32 index = 2;</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(int value) {
      
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *当前任务在任务队列中的索引
     * </pre>
     *
     * <code>int32 index = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      
      index_ = 0;
      onChanged();
      return this;
    }

    private com.example.agentgrpc.protocol.project.NodeInfo node_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.agentgrpc.protocol.project.NodeInfo, com.example.agentgrpc.protocol.project.NodeInfo.Builder, com.example.agentgrpc.protocol.project.NodeInfoOrBuilder> nodeBuilder_;
    /**
     * <code>.agent.NodeInfo node = 3;</code>
     * @return Whether the node field is set.
     */
    public boolean hasNode() {
      return nodeBuilder_ != null || node_ != null;
    }
    /**
     * <code>.agent.NodeInfo node = 3;</code>
     * @return The node.
     */
    public com.example.agentgrpc.protocol.project.NodeInfo getNode() {
      if (nodeBuilder_ == null) {
        return node_ == null ? com.example.agentgrpc.protocol.project.NodeInfo.getDefaultInstance() : node_;
      } else {
        return nodeBuilder_.getMessage();
      }
    }
    /**
     * <code>.agent.NodeInfo node = 3;</code>
     */
    public Builder setNode(com.example.agentgrpc.protocol.project.NodeInfo value) {
      if (nodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        node_ = value;
        onChanged();
      } else {
        nodeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.agent.NodeInfo node = 3;</code>
     */
    public Builder setNode(
        com.example.agentgrpc.protocol.project.NodeInfo.Builder builderForValue) {
      if (nodeBuilder_ == null) {
        node_ = builderForValue.build();
        onChanged();
      } else {
        nodeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.agent.NodeInfo node = 3;</code>
     */
    public Builder mergeNode(com.example.agentgrpc.protocol.project.NodeInfo value) {
      if (nodeBuilder_ == null) {
        if (node_ != null) {
          node_ =
            com.example.agentgrpc.protocol.project.NodeInfo.newBuilder(node_).mergeFrom(value).buildPartial();
        } else {
          node_ = value;
        }
        onChanged();
      } else {
        nodeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.agent.NodeInfo node = 3;</code>
     */
    public Builder clearNode() {
      if (nodeBuilder_ == null) {
        node_ = null;
        onChanged();
      } else {
        node_ = null;
        nodeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.agent.NodeInfo node = 3;</code>
     */
    public com.example.agentgrpc.protocol.project.NodeInfo.Builder getNodeBuilder() {
      
      onChanged();
      return getNodeFieldBuilder().getBuilder();
    }
    /**
     * <code>.agent.NodeInfo node = 3;</code>
     */
    public com.example.agentgrpc.protocol.project.NodeInfoOrBuilder getNodeOrBuilder() {
      if (nodeBuilder_ != null) {
        return nodeBuilder_.getMessageOrBuilder();
      } else {
        return node_ == null ?
            com.example.agentgrpc.protocol.project.NodeInfo.getDefaultInstance() : node_;
      }
    }
    /**
     * <code>.agent.NodeInfo node = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.agentgrpc.protocol.project.NodeInfo, com.example.agentgrpc.protocol.project.NodeInfo.Builder, com.example.agentgrpc.protocol.project.NodeInfoOrBuilder> 
        getNodeFieldBuilder() {
      if (nodeBuilder_ == null) {
        nodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.agentgrpc.protocol.project.NodeInfo, com.example.agentgrpc.protocol.project.NodeInfo.Builder, com.example.agentgrpc.protocol.project.NodeInfoOrBuilder>(
                getNode(),
                getParentForChildren(),
                isClean());
        node_ = null;
      }
      return nodeBuilder_;
    }

    private java.lang.Object downloadUrl_ = "";
    /**
     * <pre>
     *下载路径
     * </pre>
     *
     * <code>string download_url = 4;</code>
     * @return The downloadUrl.
     */
    public java.lang.String getDownloadUrl() {
      java.lang.Object ref = downloadUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        downloadUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *下载路径
     * </pre>
     *
     * <code>string download_url = 4;</code>
     * @return The bytes for downloadUrl.
     */
    public com.google.protobuf.ByteString
        getDownloadUrlBytes() {
      java.lang.Object ref = downloadUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        downloadUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *下载路径
     * </pre>
     *
     * <code>string download_url = 4;</code>
     * @param value The downloadUrl to set.
     * @return This builder for chaining.
     */
    public Builder setDownloadUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      downloadUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *下载路径
     * </pre>
     *
     * <code>string download_url = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDownloadUrl() {
      
      downloadUrl_ = getDefaultInstance().getDownloadUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *下载路径
     * </pre>
     *
     * <code>string download_url = 4;</code>
     * @param value The bytes for downloadUrl to set.
     * @return This builder for chaining.
     */
    public Builder setDownloadUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      downloadUrl_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList fileList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFileListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        fileList_ = new com.google.protobuf.LazyStringArrayList(fileList_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     *文件列表
     * </pre>
     *
     * <code>repeated string file_list = 5;</code>
     * @return A list containing the fileList.
     */
    public com.google.protobuf.ProtocolStringList
        getFileListList() {
      return fileList_.getUnmodifiableView();
    }
    /**
     * <pre>
     *文件列表
     * </pre>
     *
     * <code>repeated string file_list = 5;</code>
     * @return The count of fileList.
     */
    public int getFileListCount() {
      return fileList_.size();
    }
    /**
     * <pre>
     *文件列表
     * </pre>
     *
     * <code>repeated string file_list = 5;</code>
     * @param index The index of the element to return.
     * @return The fileList at the given index.
     */
    public java.lang.String getFileList(int index) {
      return fileList_.get(index);
    }
    /**
     * <pre>
     *文件列表
     * </pre>
     *
     * <code>repeated string file_list = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the fileList at the given index.
     */
    public com.google.protobuf.ByteString
        getFileListBytes(int index) {
      return fileList_.getByteString(index);
    }
    /**
     * <pre>
     *文件列表
     * </pre>
     *
     * <code>repeated string file_list = 5;</code>
     * @param index The index to set the value at.
     * @param value The fileList to set.
     * @return This builder for chaining.
     */
    public Builder setFileList(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFileListIsMutable();
      fileList_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件列表
     * </pre>
     *
     * <code>repeated string file_list = 5;</code>
     * @param value The fileList to add.
     * @return This builder for chaining.
     */
    public Builder addFileList(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFileListIsMutable();
      fileList_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件列表
     * </pre>
     *
     * <code>repeated string file_list = 5;</code>
     * @param values The fileList to add.
     * @return This builder for chaining.
     */
    public Builder addAllFileList(
        java.lang.Iterable<java.lang.String> values) {
      ensureFileListIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, fileList_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件列表
     * </pre>
     *
     * <code>repeated string file_list = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileList() {
      fileList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件列表
     * </pre>
     *
     * <code>repeated string file_list = 5;</code>
     * @param value The bytes of the fileList to add.
     * @return This builder for chaining.
     */
    public Builder addFileListBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureFileListIsMutable();
      fileList_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:agent.ReplaceJarReq)
  }

  // @@protoc_insertion_point(class_scope:agent.ReplaceJarReq)
  private static final com.example.agentgrpc.protocol.project.ReplaceJarReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.agentgrpc.protocol.project.ReplaceJarReq();
  }

  public static com.example.agentgrpc.protocol.project.ReplaceJarReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReplaceJarReq>
      PARSER = new com.google.protobuf.AbstractParser<ReplaceJarReq>() {
    @java.lang.Override
    public ReplaceJarReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReplaceJarReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReplaceJarReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReplaceJarReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.agentgrpc.protocol.project.ReplaceJarReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

