// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: project.proto

package com.example.agentgrpc.protocol.project;

public interface StopPrintJStacksResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.StopPrintJStacksRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *文件名
   * </pre>
   *
   * <code>string file_name = 1;</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <pre>
   *文件名
   * </pre>
   *
   * <code>string file_name = 1;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <pre>
   *文件
   * </pre>
   *
   * <code>bytes chunk = 2;</code>
   * @return The chunk.
   */
  com.google.protobuf.ByteString getChunk();
}
